### ISSUE TITLE
白天黑夜按钮

### ISSUE THREAD

**Issue by Kaiyuan-Guo** [mumu-pika/MyBlog_vuepress-theme-reco#2]
大佬，白天黑夜按钮是咋改的呀，不知道需要改的位置是哪里？（我是reco2版本）

**Comment by ghost** [comment]
> 大佬，白天黑夜按钮是咋改的呀，不知道需要改的位置是哪里？（我是reco2版本）


Did you encounter any problems? The appeal says the button is in DayAndNight.vue. where this is his click event
`updateMode() {
      if (this.currentMode === 'light') {
        let mode = 'dark'
        this.currentMode = mode
        applyMode(mode)
        localStorage.setItem('mode', mode)
      } else {
        let mode = 'light'
        this.currentMode = mode
        applyMode(mode)
        localStorage.setItem('mode', mode)
      }
    }`
